README, argument checking and help messages issues.

diff --git a/ubuntu/diaspora-bundle-install b/ubuntu/diaspora-bundle-install
--- a/ubuntu/diaspora-bundle-install
+++ b/ubuntu/diaspora-bundle-install
@@ -1,19 +1,17 @@
 #!/bin/sh
+#
+# Install  an ubuntu bundle package.
+#
+Usage='diaspora-bundle-install <diaspora-bundle-VERSION-RELEASE.tar.gz'
 
 test "$(perl -e 'print $>')" = "0" || {
     echo "You need to be root to do this, giving up"
     exit 2
 }
 
-test $# = "1" || {
-    echo "Usage: diaspora-bundle-install <diaspora-bundle-VERSION-RELEASE.tar.gz>"
-    exit 1
-}
+test $# -eq 1 || { echo $Usage; exit 2; }
 
-test -r "$1" || {
-    echo "Cannot open $1"
-    exit 2
-}
+test -r "$1" || { echo "Cannot open $1" exit 2; }
 
 rm -rf /usr/lib/diaspora-bundle
 tar xzf $1 -C /usr/lib
